# -*- coding: utf-8 -*-
"""animal_data_cleaning.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13IY36TS4n3Uqtx07QTHwtg6PsD9RvXkg
"""
#code for my data cleaning is below
'''
import pandas as pd
import numpy as np
import re
!pip install word2number
from word2number import w2n

messy_animal_data = pd.read_csv('messy_animal_data.csv')
messy_animal_data.head()

messy_animal_data.describe()

df = messy_animal_data.copy()

#create variable containing the columns we want to manipulate
columns = ['Animal','Average Speed (km/h)','Diet']
#strip whitespace from said columns
df[columns] = df[columns].apply(lambda x: x.str.strip())

#dropo rows with missing vlaues
df = df.dropna(subset=columns)

def safe_word_to_num(x):
    if isinstance(x, str):
        try:
            return w2n.word_to_num(x)
        except ValueError:
            return x
    return x

#use w2n but catch and errors
df[columns] = df[columns].apply(lambda col: col.apply(safe_word_to_num))

#specify only allowed diets
allowed_diets = ['Carnivore','Herbivore','Omnivore']
#drop rows that have a diet that isnt in the specified list
df = df[df['Diet'].isin(allowed_diets)]

#use regex to standardize speeds
def convert_speed(x):
  if not isinstance(x, str):
    return x

  parsed_x = re.findall(r'\d+' ,x)

  if len(parsed_x) == 1:
    return int(parsed_x[0])
  elif len(parsed_x) == 2:
    return ((int(parsed_x[0])+int(parsed_x[1]))/2)
  else:
    return np.nan

df['Average Speed (km/h)']= df['Average Speed (km/h)'].apply(convert_speed)
df.dropna(subset=['Average Speed (km/h)'], inplace=True)

df[columns].to_csv('jose_garcia - Cleaned Animal Data.csv', index=False)

from google.colab import files
files.download('jose_garcia - Cleaned Animal Data.csv')
'''
